<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEo3xhyx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEo3xhyx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEo3xhyx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEo3xhyx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEo3xhyx\appProdProjectContainer([
    'container.build_hash' => 'Eo3xhyx',
    'container.build_id' => '9a95ed3d',
    'container.build_time' => 1720536744,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEo3xhyx');
